pub const RECORDING_START_FAILED: &str = "RECORDING_START_FAILED";
pub const AUDIO_DEVICE_NOT_FOUND: &str = "AUDIO_DEVICE_NOT_FOUND";
pub const RECORDING_PROCESS_EXITED: &str = "RECORDING_PROCESS_EXITED";
pub const MAX_DURATION_REACHED: &str = "MAX_DURATION_REACHED";
pub const AUDIO_DEVICE_LOST: &str = "AUDIO_DEVICE_LOST";
